import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

import { BUILD_ID, PLUGIN_VERSION } from "../buildStamp";
import { isBuildId } from "../statusShape";

/**
 * WHY THIS FILE EXISTS.
 *
 * `PLUGIN_VERSION` used to be a hand-edited literal, and `BUILD_ID` did not
 * exist. Both are now generated by `scripts/stampBuild.mjs` from the plugin's
 * own sources — but the bundle is produced by Vencord's build over a symlinked
 * directory, which is not ours to hook, so the generated file is CHECKED IN.
 * A checked-in generated file is exactly the kind of thing that goes stale
 * silently, and "silently wrong while every signal says fine" is the failure
 * class this whole beacon exists to end. So staleness fails the suite.
 */

const SCRIPT = fileURLToPath(new URL("../../../../scripts/stampBuild.mjs", import.meta.url));
const PACKAGE_JSON = fileURLToPath(new URL("../../../../package.json", import.meta.url));
/** A source file that does not exist yet, used to prove the id tracks the sources. */
const PROBE = fileURLToPath(new URL("../__stampProbe.ts", import.meta.url));
/** The same probe, but somewhere that is never shipped. Not collected: not `*.test.ts`. */
const TEST_PROBE = fileURLToPath(new URL("./__stampProbe.ts", import.meta.url));

/** Runs the generator in check mode. Returns whether the stamp on disk is current. */
function stampIsCurrent(): boolean {
    try {
        execFileSync(process.execPath, [SCRIPT, "--check"], { stdio: "pipe" });
        return true;
    } catch {
        return false;
    }
}

afterEach(() => {
    // Belt and braces: the probes below remove themselves, and a crashed
    // assertion must not leave a stray module in a directory Vencord compiles.
    rmSync(PROBE, { force: true });
    rmSync(TEST_PROBE, { force: true });
});

describe("the build stamp is generated, not hand-maintained", () => {
    it("is up to date with the sources it claims to describe", () => {
        // The loud half of "make staleness loud instead of silent". If this
        // fails, run `pnpm stamp` — the plugin changed and its identity did not.
        expect(stampIsCurrent()).toBe(true);
    });

    it("goes stale the moment a shipped source changes", () => {
        // The property the whole mechanism rests on: the id is a function of the
        // bundle, so a different build cannot carry this one's identity. Asserted
        // by adding a real source file and watching the check fail — a generator
        // that silently ignored parts of the tree would let two different builds
        // share an id, and the installer would confirm the wrong one.
        expect(stampIsCurrent()).toBe(true);
        try {
            writeFileSync(PROBE, "export const STAMP_PROBE = 1;\n", "utf8");
            expect(stampIsCurrent()).toBe(false);
        } finally {
            rmSync(PROBE, { force: true });
        }
        expect(stampIsCurrent()).toBe(true);
    });

    it("does not include the test suite in the plugin's identity", () => {
        // Tests are not shipped, so editing one must not change which build is
        // running. Otherwise every test edit would invalidate an installed
        // build's recorded identity and verification would fail on a healthy
        // install — the false NEGATIVE direction, but still a lie.
        expect(existsSync(TEST_PROBE)).toBe(false);
        try {
            writeFileSync(TEST_PROBE, "export const STAMP_PROBE = 1;\n", "utf8");
            expect(stampIsCurrent()).toBe(true);
        } finally {
            rmSync(TEST_PROBE, { force: true });
        }
    });

    it("takes the version from package.json rather than a literal in the source", () => {
        const pkg = JSON.parse(readFileSync(PACKAGE_JSON, "utf8")) as { version?: string };
        expect(pkg.version).toBeTypeOf("string");
        expect(PLUGIN_VERSION).toBe(pkg.version);
    });
});

describe("BUILD_ID as an identity", () => {
    it("is a hex digest, which is what makes the field unable to carry text", () => {
        // The beacon may contain no free-form string (spec §7 — this plugin
        // reads DMs). A digest satisfies that by construction rather than by
        // the writer being careful.
        expect(BUILD_ID).toMatch(/^[0-9a-f]{16}$/);
        expect(isBuildId(BUILD_ID)).toBe(true);
    });

    it("is not the version, and not derived from it alone", () => {
        // Two builds can call themselves 0.1.0; that is precisely why
        // pluginVersion cannot serve as the identity.
        expect(BUILD_ID).not.toBe(PLUGIN_VERSION);
    });
});
