#!/usr/bin/env node
/**
 * Assemble site/index.html from the design system.
 *
 * The sections in `design/site/` are standalone previews — each is a whole HTML
 * document that links `../../tokens.css`, so a designer can open any one of them
 * on its own. The shipped site is one file with no external requests. This
 * script is the join between those two facts.
 *
 * WHY A SCRIPT AND NOT A COPY-PASTE. `docs/DESIGN-SYSTEM.md` says adopting a
 * design change should be "drop in the new files, rebuild". Hand-merging four
 * documents into one breaks that the first time anything is revised: the copy
 * in site/ silently stops matching design/, and there is no way to tell by
 * looking. Here the generated file carries a banner saying not to edit it, and
 * regenerating is one command.
 *
 * `--check` re-runs the build and fails if the result differs from what is on
 * disk, so CI (or a person) can catch a hand-edited site/index.html.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DESIGN = join(ROOT, "design");
const OUT = join(ROOT, "site", "index.html");

/** Order on the page. Not alphabetical — this is the argument the page makes. */
const SECTIONS = ["hero", "downloads", "security-warning", "privacy"];

const REPO = "surfer05/subline";

/** Everything between the outermost <style> tags. */
function styleOf(html) {
    const match = /<style>([\s\S]*?)<\/style>/.exec(html);
    return match ? match[1].trim() : "";
}

/** Everything inside <body>. buildSite wraps each section in .wrap itself (the previews don't). */
function bodyOf(html) {
    const match = /<body>([\s\S]*?)<\/body>/.exec(html);
    if (!match) throw new Error("no <body>");
    return match[1].trim();
}

/**
 * Merge the section stylesheets, keeping the first definition of each rule.
 *
 * Every preview repeats the same base rules so that it can stand alone. Emitting
 * all four copies would trade a readable stylesheet for nothing; keeping the
 * FIRST occurrence (rather than the last) means the shared base wins and a
 * section's own additions still follow it.
 */
function mergeStyles(styles) {
    const seen = new Set();
    const out = [];
    for (const sheet of styles) {
        for (const rule of topLevelRules(sheet)) {
            const trimmed = rule.trim();
            if (trimmed === "") continue;
            const key = trimmed.replace(/\s+/g, " ");
            if (seen.has(key)) continue;
            seen.add(key);
            out.push(trimmed);
        }
    }
    return out.join("\n");
}

/**
 * Split a stylesheet into TOP-LEVEL rules, respecting brace depth.
 *
 * The obvious `split(/(?<=\})/)` (split after every `}`) is wrong for any
 * nested at-rule: it cuts `@media (...) { .x {} }` in half at the inner
 * brace, and the dedup below then drops or reorders the orphaned outer `}`,
 * leaving the sheet permanently unbalanced. That is the source of every
 * "unstyled screen" and "boxes with no padding" this project has hit - the
 * installer's design.css carried two lost braces this way, hand-patched in
 * the output; this fixes it in the generator so both outputs are correct.
 *
 * A top-level rule is everything from one depth-0 position to the next: emit a
 * chunk each time the brace depth returns to zero.
 */
function topLevelRules(sheet) {
    const rules = [];
    let depth = 0;
    let start = 0;
    for (let i = 0; i < sheet.length; i++) {
        const ch = sheet[i];
        if (ch === "{") depth++;
        else if (ch === "}") {
            depth--;
            if (depth === 0) {
                rules.push(sheet.slice(start, i + 1));
                start = i + 1;
            }
        }
    }
    // Trailing content with no closing brace (a comment, or a syntax error we
    // would rather surface than swallow) rides along as its own chunk.
    if (start < sheet.length && sheet.slice(start).trim() !== "") {
        rules.push(sheet.slice(start));
    }
    return rules;
}

const tokens = readFileSync(join(DESIGN, "tokens.css"), "utf8").trim();

const parts = SECTIONS.map(name => {
    const html = readFileSync(join(DESIGN, "site", name, "index.html"), "utf8");
    return { name, style: styleOf(html), body: bodyOf(html) };
});

const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Subline — read every Discord message in your language</title>
<meta name="description" content="Subline puts a translation underneath any Discord message written in a language you don't read. It runs inside the Discord you already have.">
<meta property="og:title" content="Subline">
<meta property="og:description" content="Read what your friends are actually saying.">
<meta property="og:type" content="website">

<!-- GENERATED by scripts/buildSite.mjs from design/. Do not edit by hand:
     the next \`pnpm build:site\` will overwrite it. Change design/ instead. -->

<style>
${tokens}
</style>

<style>
${mergeStyles(parts.map(p => p.style))}
</style>
</head>
<body>

${parts.map(p => `<!-- ${p.name} -->\n<section id="${p.name}">\n<div class="wrap">\n${p.body}\n</div>\n</section>`).join("\n\n")}

<script>
(function () {
  "use strict";

  var REPO = ${JSON.stringify(REPO)};
  var RELEASES = "https://github.com/" + REPO + "/releases/latest";

  // Every download link starts pointed at the releases page and is only ever
  // REPLACED with something more specific. A blocked request, a rate-limited
  // API or an offline visitor therefore still lands somewhere that works,
  // rather than on a dead href.
  var links = [].slice.call(document.querySelectorAll("[data-dl]"));
  links.forEach(function (a) { if (!a.getAttribute("href") || a.getAttribute("href") === "#") a.href = RELEASES; });

  function set(kind, url) {
    links.filter(function (a) { return a.getAttribute("data-dl") === kind; })
         .forEach(function (a) { a.href = url; });
  }

  // GitHub's /releases/latest/download/<name> shortcut needs the literal asset
  // name, and ours carry the version — so anything hardcoded here would keep
  // serving an old build forever. Resolve at runtime instead.
  fetch("https://api.github.com/repos/" + REPO + "/releases/latest", {
    headers: { Accept: "application/vnd.github+json" }
  })
    .then(function (res) { return res.ok ? res.json() : Promise.reject(res.status); })
    .then(function (release) {
      var assets = release.assets || [];
      function find(test) {
        for (var i = 0; i < assets.length; i++) if (test(assets[i].name)) return assets[i];
        return null;
      }
      var exe = find(function (n) { return /\\.exe$/i.test(n); });
      var arm = find(function (n) { return /arm64.*\\.dmg$/i.test(n); });
      var intel = find(function (n) { return /(x64|x86_64|intel).*\\.dmg$/i.test(n); });
      var anyDmg = find(function (n) { return /\\.dmg$/i.test(n); });

      if (exe) set("win", exe.browser_download_url);
      if (arm) set("mac-arm", arm.browser_download_url);
      if (intel) set("mac-intel", intel.browser_download_url);
      // A Mac card with no matching asset keeps pointing at the releases page
      // rather than at the other architecture, which would not open.
      if (!arm && anyDmg) set("mac-arm", anyDmg.browser_download_url);

      if (release.tag_name) {
        [].forEach.call(document.querySelectorAll("[data-version]"), function (el) {
          el.textContent = release.tag_name;
          el.setAttribute("data-state", "resolved");
        });
      }
    })
    .catch(function () {
      // Links already point at the releases page. Nothing to do.
    });

  // Install tabs: swap the macOS / Windows step panels, and preselect the
  // visitor's own OS so the right steps show without a click.
  var tabs = [].slice.call(document.querySelectorAll("[data-tab]"));
  var panels = [].slice.call(document.querySelectorAll("[data-panel]"));
  function showTab(name) {
    tabs.forEach(function (t) { t.setAttribute("aria-selected", String(t.getAttribute("data-tab") === name)); });
    panels.forEach(function (pnl) { pnl.hidden = pnl.getAttribute("data-panel") !== name; });
  }
  tabs.forEach(function (t) { t.addEventListener("click", function () { showTab(t.getAttribute("data-tab")); }); });
  if (/Win/i.test(navigator.platform || navigator.userAgent)) showTab("windows");
})();
</script>

</body>
</html>
`;

/* ---------------------------------------------------------------------- *
 * The installer stylesheet
 *
 * Same join, different target. Every screen preview in design/screens/ repeats
 * the whole shell stylesheet so it can be opened standalone; the renderer needs
 * one file. Merging by first-occurrence gives the shared shell once, followed by
 * whatever each screen adds.
 *
 * Emitted into installer/src/renderer/ because that is what copyRenderer.mjs
 * ships into dist/. The renderer declares no colour of its own — docs/DESIGN-SYSTEM.md §5.
 * ---------------------------------------------------------------------- */

const SCREEN_CSS = join(ROOT, "installer", "src", "renderer", "design.css");

const screenDirs = readdirSync(join(DESIGN, "screens")).filter(name => !name.startsWith("."));
const componentDirs = readdirSync(join(DESIGN, "components")).filter(name => !name.startsWith("."));

const screenStyles = [
    ...screenDirs.map(name => styleOf(readFileSync(join(DESIGN, "screens", name, "index.html"), "utf8"))),
    ...componentDirs.map(name => styleOf(readFileSync(join(DESIGN, "components", name, "index.html"), "utf8")))
];

const rendererCss = `/* GENERATED by scripts/buildSite.mjs from design/. Do not edit by hand.
   Tokens plus the merged shell and component rules, in one file because the
   renderer loads no external stylesheet. Change design/ and rebuild. */

${tokens}

${mergeStyles(screenStyles)}
`;

if (process.argv.includes("--check")) {
    const stale = [];
    if (readFileSync(OUT, "utf8") !== page) stale.push("site/index.html");
    if (readFileSync(SCREEN_CSS, "utf8") !== rendererCss) stale.push("installer/src/renderer/design.css");
    if (stale.length > 0) {
        console.error("Out of date with design/: " + stale.join(", ") + ". Run `pnpm build:site`.");
        process.exit(1);
    }
    console.log("site/ and installer renderer match design/.");
} else {
    writeFileSync(OUT, page);
    writeFileSync(SCREEN_CSS, rendererCss);
    console.log(`Wrote site/index.html — ${SECTIONS.length} sections, ${(page.length / 1024).toFixed(1)} KB.`);
    console.log(`Wrote installer/src/renderer/design.css — ${(rendererCss.length / 1024).toFixed(1)} KB.`);
}
